### Numpy 
Numpy is array processing package. It's fundamental package for scientific computing with python.
### Array
An array is a data structure that stores values of same data type. this is the main difference between arrays and list in python, where as list contains values of different data types

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

In [8]:
## Multinested Array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [6,7,8,9,6]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [6, 7, 8, 9, 6]])

In [11]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 6, 7],
       [8, 9, 6]])

In [13]:
arr.shape

(3, 5)

### Indexing

In [15]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [6, 7, 8, 9, 6]])

In [17]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [18]:
arr[1:,3:]

array([[5, 6],
       [9, 6]])

In [20]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [23]:
arr = np.arange(0,10,2)

In [24]:
arr

array([0, 2, 4, 6, 8])

In [26]:
np.linspace(1,10,50) # Deep learning used wideky

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [33]:
# Copy function and broadcasting

In [28]:
arr

array([0, 2, 4, 6, 8])

In [31]:
arr[3:] = 100 # Broad casting

In [32]:
arr

array([  0,   2,   4, 100, 100])

In [34]:
arr1 = arr

In [35]:
arr1[3:] = 500

In [36]:
arr1

array([  0,   2,   4, 500, 500])

In [37]:
arr

array([  0,   2,   4, 500, 500])

In [38]:
arr1 = arr.copy()

In [39]:
arr1

array([  0,   2,   4, 500, 500])

In [40]:
arr1[3:] = 1000

In [41]:
arr1

array([   0,    2,    4, 1000, 1000])

In [44]:
## Some conditions useful in EDA
va1 = 2
arr/2

array([  0.,   1.,   2., 250., 250.])

In [47]:
arr[arr<1000]

array([  0,   2,   4, 500, 500])

In [49]:
np.ones(4)

array([1., 1., 1., 1.])

In [52]:
np.ones((2,4),dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [53]:
np.random.rand(3,3) # Random distrution

array([[0.25249894, 0.73301896, 0.34696004],
       [0.17274668, 0.95532735, 0.60534071],
       [0.87450938, 0.6688201 , 0.51813519]])

In [57]:
arr_example = np.random.randn(4,4) # Standard Normal distrution

In [60]:
arr_example

array([[-0.91532556, -0.62074846, -0.73335583, -0.38933428],
       [ 1.0061191 ,  0.06657299, -0.78488806,  0.20465117],
       [-1.46606596, -0.70686498,  0.7882601 , -1.22041553],
       [-1.1007212 , -0.69941027, -1.16660038, -0.09935488]])

In [66]:
np.random.randint(0,100,8)

array([48, 47,  0, 69, 66, 15, 81,  8])

In [67]:
np.random.random_sample((1,5))

array([[0.75512947, 0.63168675, 0.12466173, 0.18172179, 0.92813413]])